# Generated by Django 5.2.8 on 2025-12-28 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GuestApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_BinType',
            fields=[
                ('BinType_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('capacity_kg', models.IntegerField()),
                ('price_rs', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_District',
            fields=[
                ('District_id', models.AutoField(primary_key=True, serialize=False)),
                ('District_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_CollectionRequest',
            fields=[
                ('Request_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farmer_supply_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leftover_compost_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collection_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.collector')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.household')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_CompostBatch',
            fields=[
                ('Batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('Batch_name', models.CharField(max_length=100)),
                ('Source_Waste_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date_Created', models.DateField()),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Ready', 'Ready'), ('Sold', 'Sold')], default='Active', max_length=20)),
                ('Grade', models.CharField(choices=[('Premium', 'Premium'), ('Standard', 'Standard'), ('Basic', 'Basic')], default='Standard', max_length=20)),
                ('Stock_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=15.0, max_digits=10)),
                ('CompostManager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.compostmanager')),
            ],
            options={
                'ordering': ['-Date_Created'],
            },
        ),
        migrations.CreateModel(
            name='tbl_FarmerSupply',
            fields=[
                ('Supply_id', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Supply_Date', models.DateTimeField(auto_now_add=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('delivery_address', models.TextField()),
                ('delivery_status', models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('Collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_collectionrequest')),
                ('Farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.farmer')),
            ],
            options={
                'ordering': ['-Supply_Date'],
            },
        ),
        migrations.CreateModel(
            name='tbl_HouseholdPayment',
            fields=[
                ('Payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_for_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Completed', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_bintype')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.household')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='tbl_location',
            fields=[
                ('Location_id', models.AutoField(primary_key=True, serialize=False)),
                ('Ward_No', models.IntegerField()),
                ('Ward_Name', models.CharField(max_length=100)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_district')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Order',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Order_Date', models.DateTimeField(auto_now_add=True)),
                ('Total_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Delivery_Address', models.TextField()),
                ('Payment_Status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('Buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.farmer')),
            ],
            options={
                'ordering': ['-Order_Date'],
            },
        ),
        migrations.CreateModel(
            name='tbl_OrderItem',
            fields=[
                ('Item_id', models.AutoField(primary_key=True, serialize=False)),
                ('Item_Type', models.CharField(choices=[('Compost', 'Compost'), ('Waste', 'Direct Waste')], max_length=20)),
                ('Quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Unit_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Delivery_Status', models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('Batch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_compostbatch')),
                ('FarmerSupply_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_farmersupply')),
                ('Order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_order')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_PaymentTransaction',
            fields=[
                ('Transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('HouseholdDaily', 'Household Daily Payment'), ('CompostSale', 'Compost Sale'), ('WasteSale', 'Direct Waste Sale'), ('CollectorSalary', 'Collector Salary'), ('ManagerFee', 'Manager Processing Fee')], max_length=30)),
                ('Reference_id', models.IntegerField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Success', max_length=20)),
                ('Payer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('Receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddField(
            model_name='tbl_farmersupply',
            name='Payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.tbl_paymenttransaction'),
        ),
        migrations.CreateModel(
            name='tbl_PickupRequest',
            fields=[
                ('Pickup_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('request_time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('actual_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('UPI', 'UPI'), ('COD', 'Cash on Delivery')], max_length=20, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GuestApp.collector')),
                ('bin_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_bintype')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.household')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.tbl_householdpayment')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_residentsassociation',
            fields=[
                ('RA_id', models.AutoField(primary_key=True, serialize=False)),
                ('Association_Name', models.CharField(max_length=200)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_location')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Route',
            fields=[
                ('Route_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_house_no', models.IntegerField(blank=True, null=True, verbose_name='Start House No')),
                ('end_house_no', models.IntegerField(blank=True, null=True, verbose_name='End House No')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_location')),
                ('residents_association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_residentsassociation')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_CollectorAssignment',
            fields=[
                ('Assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=50)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.collector')),
                ('Route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_route')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_WasteInventory',
            fields=[
                ('Inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('available_quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('collection_date', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold to Farmer'), ('Composting', 'Sent to Composting')], default='Available', max_length=20)),
                ('collection_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_collectionrequest')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.collector')),
            ],
            options={
                'ordering': ['-collection_date'],
            },
        ),
    ]
