# Generated by Django 6.0 on 2025-12-23 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_District',
            fields=[
                ('District_id', models.AutoField(primary_key=True, serialize=False)),
                ('District_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_location',
            fields=[
                ('Location_id', models.AutoField(primary_key=True, serialize=False)),
                ('Ward_No', models.IntegerField()),
                ('Ward_Name', models.CharField(max_length=100)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_district')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_residentsassociation',
            fields=[
                ('RA_id', models.AutoField(primary_key=True, serialize=False)),
                ('Association_Name', models.CharField(max_length=200)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_location')),
            ],
        ),
    ]
