# Generated by Django 6.0 on 2025-12-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_District',
            fields=[
                ('District_id', models.IntegerField(primary_key=True, serialize=False)),
                ('District_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
