# Generated by Django 5.2.8 on 2025-12-31 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0002_initial'),
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_collectorassignment',
            options={'verbose_name': 'Collector Assignment', 'verbose_name_plural': 'Collector Assignments'},
        ),
        migrations.AddField(
            model_name='tbl_order',
            name='assigned_collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_waste_orders', to='GuestApp.collector'),
        ),
        migrations.AddField(
            model_name='tbl_order',
            name='assignment_status',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('Assigned', 'Assigned')], default='Unassigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_collectorassignment',
            name='Route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_route', verbose_name='Route'),
        ),
        migrations.AlterField(
            model_name='tbl_collectorassignment',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.collector', verbose_name='Collector'),
        ),
        migrations.AlterField(
            model_name='tbl_collectorassignment',
            name='day_of_week',
            field=models.CharField(max_length=50, verbose_name='Day of Week'),
        ),
        migrations.AlterUniqueTogether(
            name='tbl_collectorassignment',
            unique_together={('collector', 'Route_id', 'day_of_week')},
        ),
    ]
