# Generated by Django 6.0 on 2025-12-12 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_district',
            name='District_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='tbl_location',
            fields=[
                ('Location_id', models.AutoField(primary_key=True, serialize=False)),
                ('Ward_No', models.IntegerField()),
                ('Ward_Name', models.CharField(max_length=100)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_district')),
            ],
        ),
    ]
