# Generated by Django 5.2.8 on 2025-12-23 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0001_initial'),
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Route',
            fields=[
                ('Route_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_location')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_CollectorAssignment',
            fields=[
                ('Assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=50)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.collector')),
                ('Route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_route')),
            ],
        ),
    ]
