# Generated by Django 5.2.8 on 2025-12-23 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_tbl_route_tbl_collectorassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_route',
            name='end_house_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='End House No'),
        ),
        migrations.AddField(
            model_name='tbl_route',
            name='residents_association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_residentsassociation'),
        ),
        migrations.AddField(
            model_name='tbl_route',
            name='start_house_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Start House No'),
        ),
    ]
