# Generated by Django 5.2.8 on 2025-12-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_tbl_collectorassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_wasteinventory',
            name='salary_paid',
            field=models.BooleanField(default=False),
        ),
    ]
