# Generated by Django 6.0 on 2025-12-12 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_tbl_district_district_id_tbl_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_residentsassociation',
            fields=[
                ('RA_id', models.AutoField(primary_key=True, serialize=False)),
                ('Association_Name', models.CharField(max_length=200)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_location')),
            ],
        ),
    ]
