# Generated by Django 5.2.8 on 2025-12-23 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0002_household_house_no'),
        ('MyApp', '0003_tbl_route_end_house_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_CollectionRequest',
            fields=[
                ('Request_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farmer_supply_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leftover_compost_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collection_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.collector')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.household')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_PickupRequest',
            fields=[
                ('Pickup_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('request_time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('assigned_collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GuestApp.collector')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.household')),
            ],
        ),
    ]
