# Generated by Django 5.2.8 on 2025-12-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_tbl_wasteinventory_salary_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_compostbatch',
            name='salary_paid',
            field=models.BooleanField(default=False),
        ),
    ]
