# Generated by Django 5.2.8 on 2025-12-23 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0002_household_house_no'),
        ('MyApp', '0004_tbl_collectionrequest_tbl_pickuprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_BinType',
            fields=[
                ('BinType_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('capacity_kg', models.IntegerField()),
                ('price_rs', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='tbl_pickuprequest',
            name='actual_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tbl_pickuprequest',
            name='bin_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_bintype'),
        ),
        migrations.CreateModel(
            name='tbl_HouseholdPayment',
            fields=[
                ('Payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_for_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Completed', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_bintype')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.household')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddField(
            model_name='tbl_pickuprequest',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.tbl_householdpayment'),
        ),
    ]
