# Generated by Django 5.2.8 on 2026-01-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_tbl_compostbatch_salary_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('setting_key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('setting_value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
