# Generated by Django 5.2.8 on 2025-12-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_tbl_bintype_tbl_pickuprequest_actual_weight_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_pickuprequest',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tbl_pickuprequest',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_pickuprequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('COD', 'Cash on Delivery')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tbl_pickuprequest',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='tbl_pickuprequest',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
