# Generated by Django 5.2.8 on 2026-01-12 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_farmersupply',
            name='Collection_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_collectionrequest'),
        ),
    ]
