# Generated by Django 5.2.8 on 2026-01-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_alter_tbl_farmersupply_collection_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_wasteinventory',
            name='is_available',
        ),
        migrations.AddField(
            model_name='tbl_wasteinventory',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_compostbatch',
            name='Grade',
            field=models.CharField(choices=[('Premium', 'Premium'), ('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], default='A', max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_compostbatch',
            name='Status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Ready', 'Ready'), ('Sold', 'Sold')], default='Processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_wasteinventory',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold to Farmer'), ('Expired', 'Expired')], default='Available', max_length=20),
        ),
    ]
