# Generated by Django 5.2.8 on 2025-12-25 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0002_household_house_no'),
        ('MyApp', '0006_tbl_pickuprequest_payment_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_CompostBatch',
            fields=[
                ('Batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('Batch_name', models.CharField(max_length=100)),
                ('Source_Waste_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date_Created', models.DateField()),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Ready', 'Ready'), ('Sold', 'Sold')], default='Active', max_length=20)),
                ('Grade', models.CharField(choices=[('Premium', 'Premium'), ('Standard', 'Standard'), ('Basic', 'Basic')], default='Standard', max_length=20)),
                ('Stock_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=15.0, max_digits=10)),
                ('CompostManager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.compostmanager')),
            ],
            options={
                'ordering': ['-Date_Created'],
            },
        ),
        migrations.CreateModel(
            name='tbl_FarmerSupply',
            fields=[
                ('Supply_id', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Supply_Date', models.DateTimeField(auto_now_add=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('delivery_address', models.TextField()),
                ('delivery_status', models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('Collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_collectionrequest')),
                ('Farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.farmer')),
            ],
            options={
                'ordering': ['-Supply_Date'],
            },
        ),
        migrations.CreateModel(
            name='tbl_Order',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Order_Date', models.DateTimeField(auto_now_add=True)),
                ('Total_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Delivery_Address', models.TextField()),
                ('Payment_Status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('Buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.farmer')),
            ],
            options={
                'ordering': ['-Order_Date'],
            },
        ),
        migrations.CreateModel(
            name='tbl_OrderItem',
            fields=[
                ('Item_id', models.AutoField(primary_key=True, serialize=False)),
                ('Item_Type', models.CharField(choices=[('Compost', 'Compost'), ('Waste', 'Direct Waste')], max_length=20)),
                ('Quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Unit_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Delivery_Status', models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('Batch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_compostbatch')),
                ('FarmerSupply_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_farmersupply')),
                ('Order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_order')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_PaymentTransaction',
            fields=[
                ('Transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('HouseholdDaily', 'Household Daily Payment'), ('CompostSale', 'Compost Sale'), ('WasteSale', 'Direct Waste Sale'), ('CollectorSalary', 'Collector Salary'), ('ManagerFee', 'Manager Processing Fee')], max_length=30)),
                ('Reference_id', models.IntegerField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Pending', 'Pending')], default='Success', max_length=20)),
                ('Payer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('Receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddField(
            model_name='tbl_farmersupply',
            name='Payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.tbl_paymenttransaction'),
        ),
        migrations.CreateModel(
            name='tbl_WasteInventory',
            fields=[
                ('Inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('available_quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('collection_date', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold to Farmer'), ('Composting', 'Sent to Composting')], default='Available', max_length=20)),
                ('collection_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.tbl_collectionrequest')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.collector')),
            ],
            options={
                'ordering': ['-collection_date'],
            },
        ),
    ]
