# Generated by Django 5.2.8 on 2026-02-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_fix_grade_system_and_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_compostbatch',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
    ]
